server:
  port: 8081
  forward-headers-strategy: framework
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
      register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "https://assist.cumpleanos.com.ec"
                  - "https://apis.cumpleanos.com.ec"
                  - "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - Authorization
                  - Content-Type
                #allowCredentials: true
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          discovery:
            locator:
              enabled: true
          routes:
            - id: pos-service
              uri: lb://pos-service
              predicates:
                - Path=/pos/**
            - id: recep-service
              uri: lb://recep-service
              predicates:
                - Path=/recp/**
            - id: models-service
              uri: lb://models-service
              predicates:
                - Path=/models/**
            - id: assist-service
              uri: lb://assist-service
              predicates:
                - Path=/assist/**
            - id: meta-service
              uri: lb://meta-service
              predicates:
                - Path=/meta/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/email/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: gateway-service
    description: API Gateway
    version: 1.0