spring:
  application:
    name: meta-service

server:
  port: 8084
  forward-header-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      show-details: never
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: meta-service
    description: Microservicios para integracion con Meta
    version: 1.0