server:
  port: 9095
  forward-header-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: mongo-service

  config:
    import: classpath:/configurations/mongo-secure.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      show-details: never
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: mongo-service
    description: Gestion de modelos registrados en mongoDB
    version: 1.0