server:
  port: 9093
  forward-headers-strategy: framework

spring:
  application:
    name: recep-service

  config:
    import: classpath:/configurations/application-secure.yml

  cache:
    type: caffeine
  cloud:
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=500,expireAfterAccess=10m

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: recep-comprobantes
    description: Sistema gestor de comprobantes SRI
    version: 1.0