server:
  port: 8086
  forward-headers-strategy: framework

spring:
  application:
    name: scheduler-service

  cache:
    type: caffeine
  cloud:
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=500,expireAfterAccess=10m

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      show-details: never
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: scheduler-service
    description: Servicio de Automatizacion de tareas
    version: 1.0