server:
  port: 8082

spring:
  application:
    name: ws-service
    version: 0.01

  config:
    import: classpath:/configurations/mongo-secure.yml

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      show-details: never

info:
  app:
    name: webflux-websockets-service
    description: Sistema spring reactivo webflux
    version: 1.0