spring:
  application:
    name: pos-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"

pos:
  base-url: ${BASE_URL:http://}
  puerto: ${PUERTO_CLIENTE_POS:8080/}

file:
  path: ${DATA_SAVED_PATH:C:\\Proyectos\\Microserivicios\\data_not_saved}

logging:
  level:
    root: info
    com:
      cumpleanos:
        pos: debug
  file:
    name: ${LOG_PATH:C:\\Proyectos\\Microserivicios\\logs\\pos.log}