spring:
  application:
    name: pos-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"

pos:
  base-url: ${BASE_URL:http://}
  puerto: ${PUERTO_CLIENTE_POS:8080/}

file:
  path: ${DATA_SAVED_PATH:C:\\Proyectos\\Microserivicios\\data_not_saved}

logging:
  level:
    root: warn
    com.cumpleanos.pos: info
  file:
    name: ${LOG_PATH:C:\\Proyectos\\Microserivicios\\logs\\pos\\pos.log}
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB