spring:
  application:
    name: msvc-pos

  config:
    import: optional:configserver:http://localhost:8888

pos:
  base-url: "http://"
  puerto: ":8080/"

file:
  path: "C:\\Proyectos\\Microserivicios\\data_not_saved"