spring:
  application:
    name: pos-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"

pos:
  base-url: "http://"
  puerto: ":8080/"

file:
  path: "C:\\Proyectos\\Microserivicios\\data_not_saved"

logging:
  level:
    root: info
    com:
      cumple:
        pos: debug
  file:
    name: C:\\Proyectos\\Microserivicios\\logs\\pos\\pos.log
