spring:
  application:
    name: pos-service
  config:
    import: "optional:configserver:${CONFIG_SERVER}"

pos:
  base-url: http://
  puerto: 8080/

file:
  path: ${DATA_SAVED_PATH}

logging:
  level:
    root: info
    com:
      cumpleanos:
        pos: debug
  file:
    name: ${LOG_PATH}