package com.cumpleanos.models.utils.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Sequence {
    CLICODIGO("CLIENTE_S_CODIGO"),
    AGECODIGO("AGENTE_S_CODIGO"),
    ALMCODIGO("ALMACEN_S_CODIGO"),
    BODCODIGO("BODEGA_S_CODIGO"),
    CADAGENCODIGO("CADAGENTE_S_CODIGO"),
    CATCLICODIGO("CATCLIENTE_S_CODIGO"),
    CCOMPROBCODIGO("CCOMPROBA_S_CODIGO"),
    CENTROCODIGO("CENTRO_S_CODIGO"),
    COPCIONCODIGO("CENTRO_S_CODIGO"),
    CPARAMETCODIGO("CENTRO_S_CODIGO"),
    CUENTACODIGO("CUENTA_S_CODIGO"),
    DOPCIONCODIGO("DOPCION_S_CODIGO"),
    GPRODUCTOCODIGO("GPRODUCTO_S_CODIGO"),
    IMPUESTOCODIGO("IMPUESTO_S_CODIGO"),
    LINEACODGO("LINEA_PRODUCTO_S_CODIGO"),
    LISTAPRECODIGO("LISTAPRE_S_CODIGO"),
    MENUCODIGO("MENU_S_CODIGO"),
    POLITICACODIGO("POLITICA_S_CODIGO"),
    PRODUCTOCODIGO("PRODUCTO_S_CODIGO"),
    IMPPARTIDA("IMPPARTIDA_S_CODIGO"),
    PROGRAMACODIGO("PROGRAMA_S_CODIGO"),
    RETDATOCODIGO("RETDATO_S_CODIGO"),
    SISTEMACODIGO("SISTEMA_S_CODIGO"),
    TIPCLIENTECODIGO("TIPCLIENTE_S_CODIGO"),
    UBICACIONCODIGO("UBICACION_S_CODIGO"),
    UMEDIDACODIGO("UMEDIDA_S_CODIGO"),
    USUARIOCODIGO("USUARIO_S_CODIGO"),
    CREPOSICIONCODIGO("CREPOSICION_S_CODIGO"),
    DREPOSICIONCODIGO("DREPOSICION_S_CODIGO"),
    REPOSICIONPAGOCODIGO("REPOSICION_PAGO_S_CODIGO"),
    ;

    private final String name;
}
