server:
  port: 9090
  forward-headers-strategy: framework
spring:
  application:
    name: adiminserver-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false
info:
  app:
    name: admin-service
    description: Administrador de microservicios
    version: 1.0