server:
  port: 8081
  forward-headers-strategy: framework
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://assist.cumpleanos.com.ec"
              - "http://apis.cumpleanos.com.ec"
              - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
            #allowCredentials: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-service
          uri: lb://pos-service
          predicates:
            - Path=/pos/**
        - id: recep-service
          uri: lb://recep-service
          predicates:
            - Path=/recp/**
        - id: models-service
          uri: lb://models-service
          predicates:
            - Path=/models/**
        - id: assist-service
          uri: lb://assist-service
          predicates:
            - Path=/assist/**
        - id: meta-service
          uri: lb://meta-service
          predicates:
            - Path=/meta/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/email/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,gateway"
      exclude: "beans,env,threaddump,logfile"
  endpoint:
    health:
      show-details: never
    gateway:
      enabled: true
  info:
    env:
      enabled: false