server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-service
          uri: lb://pos-service
          predicates:
            - Path=/pos/**
        - id: recep-service
          uri: lb://recep-service
          predicates:
            - Path=/recp/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
        exclude: "beans,env,threaddump"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

info:
  app:
    name: ${spring.application.name}
    version: 1.0

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_0

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.springframework.cloud.gateway: DEBUG
