server:
  port: 9091
  forward-headers-strategy: framework

spring:
  application:
    name: models-service

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.112.46:1521/db01
    username: data_usr
    password: dataicep1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,logfile"
        exclude: "beans,env,threaddump,logfile"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0

logging:
  level:
    root: info;
    com:
      cumple:
        pos: debug
  file:
    name: C:\\Proyectos\\Microserivicios\\logs\\models.log