server:
  port: 9093

spring:
  application:
    name: msvc-inventory

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.112.46:1521/db01
    username: data_usr
    password: dataicep1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Msvc Inventory
    version: 0.0.1

logging:
  level:
    root: info;
    com:
      cumple:
        pos: debug
  file:
    name: C:\\Proyectos\\Microserivicios\\logs\\inventory.log