eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ecommerce
          uri: lb://msvc-ecommerce
          predicates:
            - Path=/ec/**
        - id: inventory
          uri: lb://msvc-inventory
          predicates:
            - Path=/inv/**
        - id: pos
          uri: lb://msvc-pos
          predicates:
            - Path=/pos/**