server:
  port: 9092
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: pos-service

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.112.46:1521/db01
    username: data_usr
    password: dataicep1
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
        exclude: "beans,env,threaddump,logfile"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

info:
  app:
    name: ${spring.application.name}

logging:
  level:
    root: info
    com.cumple.pos: debug
  file:
    name: C:\\Proyectos\\Microserivicios\\logs\\pos.log
    max-size: 10MB
    max-history: 30
  pattern:
    file:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"