server:
  port: 9093
  forward-headers-strategy: framework

spring:
  application:
    name: recep-service

  config:
    import: classpath:/configurations/application-secure.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  cloud:
    loadbalancer:
      excluded-interfaces: org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace,scheduledtasks,mappings,logfile
        exclude: beans,env,threaddump
  endpoint:
    health:
      show-details: never
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: recep-comprobantes
    description: Sistema gestor de comprobantes SRI
    version: 1.0
