server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: scheduler-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info,logfile
        exclude: beans,threaddump
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always
    info:
      env:
        enabled: true

info:
  app:
    name: ${spring.application.name }:scheduler-service